# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  sonar-project-key:
    description: 'sonar project key'
    required: true
  sonar-host-url:
    description: 'Sonar server URL'
    required: true
    default: 'sonarcube.com'    
  sonar-login:
    description: 'Sonar token'
    required: true
    default: 'sometokenvalue'       
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'docker://sonarsource/sonar-scanner-cli'
  args:
    - 'sonar-scanner'
    - '-Dsonar.projectKey=${{ inputs.sonar-project-key }}'
    - '-Dsonar.host.url=${{ inputs.sonar-host-url }}'
    - '-Dsonar.login=${{ inputs.sonar-login }}'
